apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-container
        image: your-docker-repo/fastapi-prometheus:latest
        ports:
        - containerPort: 8000
        - containerPort: 8001  # Porta para métricas Prometheus
