apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
    - protocol: TCP
      port: 8001
      targetPort: 8001  # Porta para métricas Prometheus
  type: LoadBalancer
