apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fastapi-deployment
  namespace: default
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-container
        image: kailima/fastapi-app:latest
        ports:
        - containerPort: 8000
        - containerPort: 8001
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
  strategy:
    canary:
      canaryService: fastapi-canary
      stableService: fastapi-stable
      steps:
      - setWeight: 10
      - pause: {duration: 2m}
      - setWeight: 30
      - pause: {duration: 3m}
      - setWeight: 50
      - pause: {duration: 3m}
      - setWeight: 100
