apiVersion: v1
kind: Service
metadata:
  name: fastapi-stable
  namespace: default
spec:
  selector:
    app: fastapi-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: metrics
      protocol: TCP
      port: 8001
      targetPort: 8001

apiVersion: v1
kind: Service
metadata:
  name: fastapi-canary
  namespace: default
spec:
  selector:
    app: fastapi-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: metrics
      protocol: TCP
      port: 8001
      targetPort: 8001